package com.beyzanur.simpracasestudy.domain.exception;

public enum ExceptionDescription {
    CHECK_IN_DATE_CANNOT_BE_EMPTY,

    FIRST_NAME_CANNOT_BE_EMPTY,
    LAST_NAME_CANNOT_BE_EMPTY,
    EMAIL_CANNOT_BE_EMPTY,
    PHONE_NUMBER_CANNOT_BE_EMPTY,
    CHECK_OUT_DATE_CANNOT_BE_EMPTY,
    CHECK_IN_DATE_CANNOT_BE_AFTER_CHECK_OUT_DATE,
    ROOM_CODE_CANNOT_BE_FOUND,
    ENTITY_NOT_FOUND,
    RATE_CODE_CANNOT_BE_FOUND, TOTAL_PAX_CANNOT_BE_LESS_THAN_ONE, RATE_CODE_CANNOT_BE_NULL, ROOM_CODE_CANNOT_BE_NULL, RESERVATION_ID_NOT_VALID;
}
